In [11]:
#task1
import numpy as np
a=np.arange(1,6)
print(a)
np.insert(np.arange(1,6),np.repeat(np.arange(1,5),3),0)
#np.insert(np.arange(1,6),[1,2],0)
#np.repeat(np.arange(1,5),3)

[1 2 3 4 5]


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [29]:
#task2
#1-sposob
a=np.zeros((8,8))
a[0:-1:2,1:-1:2]=1
a[1:-1:2,0:-1:2]=1
print(a)

#2-sposob
np.indices((8,8)).sum(axis=0)


[[0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

In [36]:
#task3
a=np.random.random((5,5))
print(a)
b=(a-a.mean(axis=1).reshape((-1,1))).mean(axis=1) #iz matrix vuchli ctolbik srednih po strokam
print(b)

[[0.57369563 0.50528403 0.65959718 0.83709018 0.73715661]
 [0.85524384 0.48965802 0.2469346  0.99823355 0.57380167]
 [0.97191758 0.39991683 0.24086396 0.36590111 0.43772825]
 [0.03079238 0.28922307 0.59421168 0.10025818 0.81741454]
 [0.0160171  0.74997408 0.15297984 0.25938346 0.09601938]]
[-2.22044605e-17  4.44089210e-17 -4.44089210e-17 -4.44089210e-17
  4.44089210e-17]


In [47]:
#task4
a=np.zeros((4,5))+np.arange(0,40,10).reshape((-1,1))+np.arange(5)

print(a)


[[ 0.  1.  2.  3.  4.]
 [10. 11. 12. 13. 14.]
 [20. 21. 22. 23. 24.]
 [30. 31. 32. 33. 34.]]
